//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4927
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tencent.OA.DocEncyclic.Contract.Entity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doc", Namespace="http://schemas.datacontract.org/2004/07/Tencent.OA.DocEncyclic.Contract.Entity")]
    public partial class Doc : Tencent.OA.DocEncyclic.Contract.Entity.BusinessBaseOfguid
    {
        
        private string CcIDListField;
        
        private string CcListField;
        
        private System.Nullable<int> ClickCountField;
        
        private System.DateTime CreationTimeField;
        
        private string CreationTimeDisplayField;
        
        private int CreatorIDField;
        
        private string CreatorNameField;
        
        private string DeptIDField;
        
        private string DeptNameField;
        
        private string DocCodeField;
        
        private string DocPreviewURLField;
        
        private System.Nullable<int> DocStatusField;
        
        private System.Nullable<System.Guid> DocSubTypeIDField;
        
        private string DocSummaryField;
        
        private string DocTitleField;
        
        private string DocTopicField;
        
        private System.Guid DocTypeIDField;
        
        private string DocTypeNameField;
        
        private System.Nullable<int> DownloadCountField;
        
        private string DownloadURLField;
        
        private System.Nullable<int> DutyerIDField;
        
        private string DutyerNameField;
        
        private int IsSendMailField;
        
        private int IsSerectField;
        
        private System.Nullable<System.Guid> LastModifyDocIDField;
        
        private string PreviewURLField;
        
        private System.Nullable<int> ShowInOtherSysField;
        
        private int SingleNotifyField;
        
        private string SysDeptIDField;
        
        private string SysDeptNameField;
        
        private string ToIDListField;
        
        private string ToListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcIDList
        {
            get
            {
                return this.CcIDListField;
            }
            set
            {
                this.CcIDListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcList
        {
            get
            {
                return this.CcListField;
            }
            set
            {
                this.CcListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClickCount
        {
            get
            {
                return this.ClickCountField;
            }
            set
            {
                this.ClickCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime
        {
            get
            {
                return this.CreationTimeField;
            }
            set
            {
                this.CreationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationTimeDisplay
        {
            get
            {
                return this.CreationTimeDisplayField;
            }
            set
            {
                this.CreationTimeDisplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorID
        {
            get
            {
                return this.CreatorIDField;
            }
            set
            {
                this.CreatorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorName
        {
            get
            {
                return this.CreatorNameField;
            }
            set
            {
                this.CreatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptID
        {
            get
            {
                return this.DeptIDField;
            }
            set
            {
                this.DeptIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName
        {
            get
            {
                return this.DeptNameField;
            }
            set
            {
                this.DeptNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocCode
        {
            get
            {
                return this.DocCodeField;
            }
            set
            {
                this.DocCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocPreviewURL
        {
            get
            {
                return this.DocPreviewURLField;
            }
            set
            {
                this.DocPreviewURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DocStatus
        {
            get
            {
                return this.DocStatusField;
            }
            set
            {
                this.DocStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DocSubTypeID
        {
            get
            {
                return this.DocSubTypeIDField;
            }
            set
            {
                this.DocSubTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocSummary
        {
            get
            {
                return this.DocSummaryField;
            }
            set
            {
                this.DocSummaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTitle
        {
            get
            {
                return this.DocTitleField;
            }
            set
            {
                this.DocTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTopic
        {
            get
            {
                return this.DocTopicField;
            }
            set
            {
                this.DocTopicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DocTypeID
        {
            get
            {
                return this.DocTypeIDField;
            }
            set
            {
                this.DocTypeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTypeName
        {
            get
            {
                return this.DocTypeNameField;
            }
            set
            {
                this.DocTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DownloadCount
        {
            get
            {
                return this.DownloadCountField;
            }
            set
            {
                this.DownloadCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DownloadURL
        {
            get
            {
                return this.DownloadURLField;
            }
            set
            {
                this.DownloadURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DutyerID
        {
            get
            {
                return this.DutyerIDField;
            }
            set
            {
                this.DutyerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DutyerName
        {
            get
            {
                return this.DutyerNameField;
            }
            set
            {
                this.DutyerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSendMail
        {
            get
            {
                return this.IsSendMailField;
            }
            set
            {
                this.IsSendMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSerect
        {
            get
            {
                return this.IsSerectField;
            }
            set
            {
                this.IsSerectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> LastModifyDocID
        {
            get
            {
                return this.LastModifyDocIDField;
            }
            set
            {
                this.LastModifyDocIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviewURL
        {
            get
            {
                return this.PreviewURLField;
            }
            set
            {
                this.PreviewURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShowInOtherSys
        {
            get
            {
                return this.ShowInOtherSysField;
            }
            set
            {
                this.ShowInOtherSysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SingleNotify
        {
            get
            {
                return this.SingleNotifyField;
            }
            set
            {
                this.SingleNotifyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SysDeptID
        {
            get
            {
                return this.SysDeptIDField;
            }
            set
            {
                this.SysDeptIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SysDeptName
        {
            get
            {
                return this.SysDeptNameField;
            }
            set
            {
                this.SysDeptNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToIDList
        {
            get
            {
                return this.ToIDListField;
            }
            set
            {
                this.ToIDListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToList
        {
            get
            {
                return this.ToListField;
            }
            set
            {
                this.ToListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessBaseOfguid", Namespace="http://schemas.datacontract.org/2004/07/Tencent.OA.DocEncyclic.Contract.Entity")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.Doc))]
    public partial class BusinessBaseOfguid : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShowInOtherSys", Namespace="http://schemas.datacontract.org/2004/07/Tencent.OA.DocEncyclic.Contract.Entity")]
    public enum ShowInOtherSys : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoShow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Show = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ignore = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDocService")]
public interface IDocService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/UpateDocDownCnts", ReplyAction="http://tempuri.org/IDocService/UpateDocDownCntsResponse")]
    int UpateDocDownCnts(string pDocID, int pCnt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/UpateDocClickCnts", ReplyAction="http://tempuri.org/IDocService/UpateDocClickCntsResponse")]
    int UpateDocClickCnts(string pDocID, int pCnt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetAll", ReplyAction="http://tempuri.org/IDocService/GetAllResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/Save", ReplyAction="http://tempuri.org/IDocService/SaveResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.Doc[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.Doc))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.BusinessBaseOfguid))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys))]
    object Save(Tencent.OA.DocEncyclic.Contract.Entity.Doc pDocEtt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/UpdateDoc", ReplyAction="http://tempuri.org/IDocService/UpdateDocResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc UpdateDoc(Tencent.OA.DocEncyclic.Contract.Entity.Doc pDocEtt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/UpdateAndInsert", ReplyAction="http://tempuri.org/IDocService/UpdateAndInsertResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.Doc[]))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.Doc))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.BusinessBaseOfguid))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys))]
    object UpdateAndInsert(Tencent.OA.DocEncyclic.Contract.Entity.Doc[] pTwoDocEtt);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetLatestDoc", ReplyAction="http://tempuri.org/IDocService/GetLatestDocResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetLatestDoc(int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetLatestDocByQuery", ReplyAction="http://tempuri.org/IDocService/GetLatestDocByQueryResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetLatestDocByQuery(int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys showInOtherSys, string query);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocByDocTypeID", ReplyAction="http://tempuri.org/IDocService/GetDocByDocTypeIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDocTypeID(System.Guid pDocTypeID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocByDocTypeID2", ReplyAction="http://tempuri.org/IDocService/GetDocByDocTypeID2Response")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDocTypeID2(System.Guid pDocTypeID, System.Guid pDocSubTypeID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocByDutyerID", ReplyAction="http://tempuri.org/IDocService/GetDocByDutyerIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDutyerID(int pDutyerID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetFavouriteDoc", ReplyAction="http://tempuri.org/IDocService/GetFavouriteDocResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetFavouriteDoc(int pFocuserID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetByDocID", ReplyAction="http://tempuri.org/IDocService/GetByDocIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc GetByDocID(System.Guid pDocID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetByLastModifyDocID", ReplyAction="http://tempuri.org/IDocService/GetByLastModifyDocIDResponse")]
    string GetByLastModifyDocID(System.Guid pDocID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocByDeptID", ReplyAction="http://tempuri.org/IDocService/GetDocByDeptIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDeptID(string pDeptID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocBySystemID", ReplyAction="http://tempuri.org/IDocService/GetDocBySystemIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocBySystemID(System.Guid pDocTypeID, string pSystemDeptID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataByTypeID", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataByTypeIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByTypeID(out int pItemCount, string pTypeID, string pSubTypeID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataBySelfPublish", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataBySelfPublishResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySelfPublish(out int pItemCount, string pStaffID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataByFavourite", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataByFavouriteResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByFavourite(out int pItemCount, string pFavouriteStaffID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataByDeptID", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataByDeptIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByDeptID(out int pItemCount, string pDocTypeID, string pDeptID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataBySystemIDOrDeptID", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataBySystemIDOrDeptIDResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySystemIDOrDeptID(out int pItemCount, string pDocTypeID, string pSystemDeptID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataBySearchProc", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataBySearchProcResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySearchProc(out int pItemCount, string pDocTitle, string pDocTopic, string pDocSummary, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataByAdvSearchProc", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataByAdvSearchProcResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByAdvSearchProc(out int pItemCount, string pDocTopic, string pDocSummary, string pDocCreatorName, string pPublishDateFrom, string pPublishDateTo, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataBySelfSystem", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataBySelfSystemResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySelfSystem(out int pItemCount, string pTypeID, int SystemDeptID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetDocPagedDataByOtherSystem", ReplyAction="http://tempuri.org/IDocService/GetDocPagedDataByOtherSystemResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByOtherSystem(out int pItemCount, string pTypeID, int SystemDeptID, int pPageSize, int pCurrentPage);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocService/GetSendMailDoc", ReplyAction="http://tempuri.org/IDocService/GetSendMailDocResponse")]
    Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetSendMailDoc(int pIsSendMail, int pSingleNotify);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDocServiceChannel : IDocService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DocServiceClient : System.ServiceModel.ClientBase<IDocService>, IDocService
{
    
    public DocServiceClient()
    {
    }
    
    public DocServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DocServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DocServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DocServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int UpateDocDownCnts(string pDocID, int pCnt)
    {
        return base.Channel.UpateDocDownCnts(pDocID, pCnt);
    }
    
    public int UpateDocClickCnts(string pDocID, int pCnt)
    {
        return base.Channel.UpateDocClickCnts(pDocID, pCnt);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetAll()
    {
        return base.Channel.GetAll();
    }
    
    public object Save(Tencent.OA.DocEncyclic.Contract.Entity.Doc pDocEtt)
    {
        return base.Channel.Save(pDocEtt);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc UpdateDoc(Tencent.OA.DocEncyclic.Contract.Entity.Doc pDocEtt)
    {
        return base.Channel.UpdateDoc(pDocEtt);
    }
    
    public object UpdateAndInsert(Tencent.OA.DocEncyclic.Contract.Entity.Doc[] pTwoDocEtt)
    {
        return base.Channel.UpdateAndInsert(pTwoDocEtt);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetLatestDoc(int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetLatestDoc(pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetLatestDocByQuery(int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys showInOtherSys, string query)
    {
        return base.Channel.GetLatestDocByQuery(pMaxResults, showInOtherSys, query);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDocTypeID(System.Guid pDocTypeID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetDocByDocTypeID(pDocTypeID, pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDocTypeID2(System.Guid pDocTypeID, System.Guid pDocSubTypeID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetDocByDocTypeID2(pDocTypeID, pDocSubTypeID, pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDutyerID(int pDutyerID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetDocByDutyerID(pDutyerID, pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetFavouriteDoc(int pFocuserID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetFavouriteDoc(pFocuserID, pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc GetByDocID(System.Guid pDocID)
    {
        return base.Channel.GetByDocID(pDocID);
    }
    
    public string GetByLastModifyDocID(System.Guid pDocID)
    {
        return base.Channel.GetByLastModifyDocID(pDocID);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocByDeptID(string pDeptID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetDocByDeptID(pDeptID, pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocBySystemID(System.Guid pDocTypeID, string pSystemDeptID, int pMaxResults, Tencent.OA.DocEncyclic.Contract.Entity.ShowInOtherSys pShowInOtherSys)
    {
        return base.Channel.GetDocBySystemID(pDocTypeID, pSystemDeptID, pMaxResults, pShowInOtherSys);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByTypeID(out int pItemCount, string pTypeID, string pSubTypeID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataByTypeID(out pItemCount, pTypeID, pSubTypeID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySelfPublish(out int pItemCount, string pStaffID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataBySelfPublish(out pItemCount, pStaffID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByFavourite(out int pItemCount, string pFavouriteStaffID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataByFavourite(out pItemCount, pFavouriteStaffID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByDeptID(out int pItemCount, string pDocTypeID, string pDeptID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataByDeptID(out pItemCount, pDocTypeID, pDeptID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySystemIDOrDeptID(out int pItemCount, string pDocTypeID, string pSystemDeptID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataBySystemIDOrDeptID(out pItemCount, pDocTypeID, pSystemDeptID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySearchProc(out int pItemCount, string pDocTitle, string pDocTopic, string pDocSummary, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataBySearchProc(out pItemCount, pDocTitle, pDocTopic, pDocSummary, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByAdvSearchProc(out int pItemCount, string pDocTopic, string pDocSummary, string pDocCreatorName, string pPublishDateFrom, string pPublishDateTo, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataByAdvSearchProc(out pItemCount, pDocTopic, pDocSummary, pDocCreatorName, pPublishDateFrom, pPublishDateTo, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataBySelfSystem(out int pItemCount, string pTypeID, int SystemDeptID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataBySelfSystem(out pItemCount, pTypeID, SystemDeptID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetDocPagedDataByOtherSystem(out int pItemCount, string pTypeID, int SystemDeptID, int pPageSize, int pCurrentPage)
    {
        return base.Channel.GetDocPagedDataByOtherSystem(out pItemCount, pTypeID, SystemDeptID, pPageSize, pCurrentPage);
    }
    
    public Tencent.OA.DocEncyclic.Contract.Entity.Doc[] GetSendMailDoc(int pIsSendMail, int pSingleNotify)
    {
        return base.Channel.GetSendMailDoc(pIsSendMail, pSingleNotify);
    }
}
